---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-frontend
data:
  nginx.conf: |
    server {

      listen {{ .Values.appContainerPort }};

      location /momo-store {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
      }
      
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }

      location ~ /(products|categories|orders|auth/whoami|metrics) {
        proxy_pass http://{{ .Values.proxy.host }}:{{ .Values.proxy.port }};
      }

    }