apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-frontend
  namespace: momo-store
data:
  nginx.conf: |
    server {
      listen 8080;

      location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
      }

      location ~ /(products|categories|orders|auth/whoami|metrics) {
        proxy_pass http://backend:8081;
      }
    }
