---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config-frontend
data:
  nginx.conf: |
    upstream myproxy {
      server backend:8081;
    }

    server {
        listen 80;

        location / {
            root   /app;
            index  index.html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://myproxy/;
        }
    }