apiVersion: v1
kind: Service
metadata:
  namespace: momo-store
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.serviceContainerPort }}
      protocol: TCP
      targetPort: {{ .Values.serviceContainerTargerPort }}
  selector:
    app: {{ .Chart.Name }}
