apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 9093
      protocol: TCP
  selector:
    app: alertmanager
  sessionAffinity: None
  type: ClusterIP
