---
groups:
  - name: Momo store rules
    rules:

    # - alert: InstanceDownBackend
    #   expr: up{app="backend"} == 0
    #   for: 1m
    #   labels:
    #     severity: critical
    #     project: "momo_store"
    #     component: "Backend"

    # - alert: InstanceDownFrontend
    #   expr: up{app="frontend"} == 0
    #   for: 1m
    #   labels:
    #     severity: critical
    #     project: "momo_store"
    #     component: "frontend"

    # - alert: HTTPServerError500
    #   expr: http_requests_total{status="500"} > 0
    #   for: 1m
    #   labels:
    #     severity: critical
    #   annotations:
    #     summary: "HTTP 500 Internal Server Error"
    #     description: "Detected HTTP 500 errors on the server."

    # - alert: HighDelayPOSTRequests
    #   expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket{method="POST", status="200", uri="/orders"}[5m])) > 0.1
    #   for: 5m
    #   labels:
    #     severity: warning
    #   annotations:
    #     summary: "High Delay in POST Requests"
    #     description: "Detected high delay (95th percentile > 100ms) for successful POST requests to /orders over the last 5 minutes."

    # - alert: ActuatorPrometheusError
    #   expr: http_server_requests_seconds{uri="/actuator/prometheus"} > 0 and http_server_requests_seconds{status!="200", uri="/actuator/prometheus"} > 0
    #   for: 2m
    #   labels:
    #     severity: warning
    #   annotations:
    #     summary: "Actuator Prometheus Endpoint Error"
    #     description: "Detected errors on /actuator/prometheus endpoint in the last 2 minutes."
  
    # - alert: SuccessfulGETRequest
    #   expr: http_server_requests_seconds_count{method="GET", status="200", uri="/products"} > 0
    #   for: 1m
    #   labels:
    #     severity: critical
    #   annotations:
    #     summary: "Successful GET request on /products"
        
    - alert: AllClear
      expr: vector(1)
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "std-021-024 Prometheus/Alertmanager Systems Operational"
        description: "The Prometheus Heartbreak is ok."

    - alert: TargetDownFront
      expr: up{job="momo-store-frontend"} < 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "std-021-024 / Target {{ $labels.namespace }}/{{ $labels.pod }} is down for more than 1 minute."
        description: "The target {{ $labels.namespace }}/{{ $labels.pod }} is down for more than 1 minute."

    - alert: TargetDownBack
      expr: up{job="momo-store-backend"} < 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "std-021-024 / Target {{ $labels.namespace }}/{{ $labels.pod }} is down for more than 1 minute."
        description: "The target {{ $labels.namespace }}/{{ $labels.pod }} is down for more than 1 minute."

