{
 "title": "Business Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Date/Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 20, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "timestamp(up{instance=\"frontend.momo-store.svc.cluster.local:80\",job=\"momo-store-frontend\"}) * 1000"
    }
   ]
  },
  {
   "title": "Заявок создано",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "requests_count{app=\"backend\"}"
    }
   ]
  },
  {
   "title": "Заказов сделано",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "orders_count{app=\"backend\"}"
    }
   ]
  },
  {
   "title": "График Заказа Пельмешек",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 14, "x": 6, "y": 3 },
   "targets": [
    {
     "expr": "sum(rate(dumplings_listing_count{app=\"backend\", kubernetes_namespace=\"momo-store\"}[5m])) by (id)\r\n"
    }
   ]
  },
  {
   "title": "Всего пельмешек заказано",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dumplings_listing_count{app=\"backend\", kubernetes_namespace=\"momo-store\"})"
    }
   ]
  }
 ]
}