{
 "title": "Infrastucture Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "master_cpu_utilization_percent{}"
    }
   ]
  },
  {
   "title": "CPU Utilization in percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "master_cpu_utilization_percent{}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "master_cpu_utilization_percent{}"
    }
   ]
  },
  {
   "title": "Memory Utilization in percent",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "master_memory_utilization_percent{}"
    }
   ]
  },
  {
   "title": "Pod Volume Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(pod_volume_utilization)" }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_network_received_bytes_count[5m])"
    },
    {
     "expr": "rate(node_network_sent_bytes_count[5m])"
    }
   ]
  },
  {
   "title": "Response timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(response_timing_ms_sum{app=\"backend\"}[5m])"
    }
   ]
  }
 ]
}