{
 "title": "Logs dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Backend Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"backend\"}"
    }
   ]
  },
  {
   "title": "Nginx Ingress Log",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"ingress-nginx\"}"
    }
   ]
  },
  {
   "title": "FrontEnd Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{app=\"frontend\"}"
    }
   ]
  },
  {
   "title": "CertManager Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"cert-manager\"}"
    }
   ]
  },
  {
   "title": "Argo-CD Logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{app=\"argocd-server\"}"
    }
   ]
  },
  {
   "title": "Grafana logs",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "{app=\"grafana\"}"
    },
    {}
   ]
  }
 ]
}